name: Build MSVC Project

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive # Скачивает зависимости (например, имгуи или дампер), если они подключены

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      run: |
        msbuild CS2_External/CS2_External.vcxproj /p:Configuration=Release /p:Platform=x64
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Compiled-Executable
        path: |
          **/Release/*.exe
          **/Release/*.dll
          
